---
- name: Install Amazon Corretto and Docker
  hosts: your_amazon_linux_server
  become: true  # Run tasks as sudo

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest

    - name: Install Amazon Corretto 11
      yum:
        name: java-11-amazon-corretto-devel
        state: present

    - name: Add Docker Yum repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Gitflow
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
